"""Shared pytest fixtures for the Sarvik (ksp-saathi) integration suite.

These fixtures cover three layers:

1.  **Unit fixtures** (always-on, mocked) — ``mock_catalyst_client``,
    ``mock_gemini``, ``mock_neo4j``. These swap network-dependent helpers
    for in-memory fakes so the unit-tagged tests stay hermetic.
2.  **Data fixtures** — ``sample_firs`` reads
    ``data/firs_sample.jsonl`` once per session and returns parsed dicts.
3.  **Auth fixtures** — ``test_user_token`` is a factory that mints a
    fake JWT-shaped token for any of the three demo roles (PSI, SHO,
    DCP). Real Catalyst Auth is never called; ``mock_rbac_decode``
    decodes the fake tokens back to a role + scope.

Anything you add here is auto-discovered by every test module under
``app/tests/``.
"""

from __future__ import annotations

import base64
import json
import os
from pathlib import Path
from typing import Any, Callable, Iterable

import pytest


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = REPO_ROOT / "data"
FIRS_SAMPLE_PATH = DATA_DIR / "firs_sample.jsonl"
FIXTURES_DIR = Path(__file__).resolve().parent / "fixtures"
GOLDEN_QUERIES_PATH = FIXTURES_DIR / "queries" / "golden.json"
AUDIO_FIXTURES_DIR = FIXTURES_DIR / "audio"


# ---------------------------------------------------------------------------
# Data fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def sample_firs() -> list[dict[str, Any]]:
    """Parse data/firs_sample.jsonl once per test session.

    The sample is the first 100 records from the 50k synthetic FIR corpus
    (generated by ``data/generate_synthetic_firs.py``). Tests should treat
    this as read-only.
    """
    if not FIRS_SAMPLE_PATH.exists():
        pytest.skip(f"firs_sample.jsonl not found at {FIRS_SAMPLE_PATH}")
    records: list[dict[str, Any]] = []
    with FIRS_SAMPLE_PATH.open("r", encoding="utf-8") as handle:
        for line_no, raw in enumerate(handle, 1):
            raw = raw.strip()
            if not raw:
                continue
            try:
                records.append(json.loads(raw))
            except json.JSONDecodeError as exc:  # pragma: no cover — defensive
                pytest.fail(f"firs_sample.jsonl line {line_no} not JSON: {exc}")
    return records


@pytest.fixture(scope="session")
def golden_queries() -> list[dict[str, Any]]:
    """Load the 30 representative bilingual queries used in eval."""
    if not GOLDEN_QUERIES_PATH.exists():
        pytest.skip(f"golden.json not found at {GOLDEN_QUERIES_PATH}")
    return json.loads(GOLDEN_QUERIES_PATH.read_text(encoding="utf-8"))["queries"]


# ---------------------------------------------------------------------------
# Mock Catalyst client
# ---------------------------------------------------------------------------

class FakeCatalystClient:
    """In-memory stand-in for ``shared.catalyst_client``.

    Mimics the methods that the real client exposes:

    * ``quickml_llm(prompt, model)``      — canned LLM completions
    * ``data_store_query(sql)``           — canned SQL row sets
    * ``invoke_function(name, payload)``  — canned Catalyst Function calls
    * ``append_audit(step)``              — captures audit chain in-memory

    Tests can prime expected outputs via the ``responses`` dict and
    afterwards inspect ``calls`` to verify what was asked of it.
    """

    def __init__(self) -> None:
        self.responses: dict[str, Any] = {}
        self.calls: list[tuple[str, Any]] = []
        self.audit_chain: list[dict[str, Any]] = []
        self.fail_on: set[str] = set()  # names that should raise

    # ---- LLM ----
    def quickml_llm(self, prompt: str, model: str = "qwen2.5-7b") -> str:
        self.calls.append(("quickml_llm", {"prompt": prompt, "model": model}))
        if "quickml_llm" in self.fail_on:
            raise RuntimeError("quickml_llm forced failure")
        return self.responses.get(
            "quickml_llm",
            '{"intent":"lookup","language":"en","confidence":0.5,"entities":{}}',
        )

    # ---- Data Store ----
    def data_store_query(self, sql: str, params: dict | None = None) -> list[dict]:
        self.calls.append(("data_store_query", {"sql": sql, "params": params}))
        if "data_store_query" in self.fail_on:
            raise RuntimeError("data_store_query forced failure")
        return self.responses.get("data_store_query", [])

    # ---- Function fan-out ----
    def invoke_function(self, name: str, payload: dict) -> dict:
        self.calls.append((f"invoke:{name}", payload))
        if name in self.fail_on:
            raise RuntimeError(f"{name} forced failure")
        return self.responses.get(f"invoke:{name}", {})

    # ---- Audit ----
    def append_audit(self, step: dict) -> dict:
        self.calls.append(("append_audit", step))
        idx = len(self.audit_chain)
        record = {"step_index": idx, **step}
        self.audit_chain.append(record)
        return {"ok": True, "step_index": idx}


@pytest.fixture
def mock_catalyst_client() -> FakeCatalystClient:
    """Fresh FakeCatalystClient per-test (state never leaks across tests)."""
    return FakeCatalystClient()


# ---------------------------------------------------------------------------
# Mock Gemini
# ---------------------------------------------------------------------------

class FakeGeminiClient:
    """In-memory stand-in for ``shared.gemini_client``.

    Handles three call shapes used in the codebase:

    * ``generate(prompt, language)`` — Kannada/English synthesis
    * ``embed(text)``                — multilingual embedding
    * ``live_stream(audio_bytes)``   — Gemini Live STT+TTS round trip
    """

    def __init__(self) -> None:
        self.responses: dict[str, Any] = {}
        self.calls: list[tuple[str, Any]] = []
        # Sensible defaults so synthesizer tests don't have to wire each time.
        self.responses.setdefault("generate", "Synthesized answer.")
        self.responses.setdefault("generate_kn", "ಸಂಶ್ಲೇಷಿತ ಉತ್ತರ.")
        self.responses.setdefault("embed", [0.0] * 768)
        self.responses.setdefault(
            "live_stream",
            {"transcript": "test transcript", "audio_b64": "AAAA",
             "language": "en"},
        )

    def generate(self, prompt: str, language: str = "en") -> str:
        self.calls.append(("generate", {"prompt": prompt, "language": language}))
        if language == "kn":
            return self.responses.get("generate_kn", self.responses["generate"])
        return self.responses["generate"]

    def embed(self, text: str) -> list[float]:
        self.calls.append(("embed", text))
        return self.responses["embed"]

    def live_stream(self, audio_bytes: bytes, language_hint: str = "auto") -> dict:
        self.calls.append(("live_stream", {"bytes": len(audio_bytes),
                                           "lang_hint": language_hint}))
        return self.responses["live_stream"]


@pytest.fixture
def mock_gemini() -> FakeGeminiClient:
    return FakeGeminiClient()


# ---------------------------------------------------------------------------
# Mock Neo4j
# ---------------------------------------------------------------------------

class FakeNeo4jSession:
    """Minimal Neo4j session stand-in.

    Sets up a tiny in-memory graph with three accused, one shared FIR, and
    a kingpin link so cypher tests can assert structural traversal results
    without hitting AuraDB.
    """

    def __init__(self) -> None:
        self.queries: list[tuple[str, dict | None]] = []
        # Default canned graph response — overridable by tests.
        self.canned: dict[str, Any] = {
            "nodes": [
                {"id": "p1", "name": "Manpreet Chowdary", "type": "Accused"},
                {"id": "p2", "name": "Ahmed Naik", "type": "Accused"},
                {"id": "f1", "name": "MGR/2025/00001", "type": "FIR"},
            ],
            "edges": [
                {"source": "p1", "target": "f1", "type": "ACCUSED_IN"},
                {"source": "p2", "target": "f1", "type": "LINKED_TO"},
            ],
        }
        self.fail = False

    def run(self, query: str, params: dict | None = None) -> Any:
        self.queries.append((query, params))
        if self.fail:
            raise RuntimeError("neo4j unavailable")
        return self.canned

    def close(self) -> None:  # pragma: no cover — symmetry with real driver
        pass

    def __enter__(self):  # pragma: no cover — context-manager parity
        return self

    def __exit__(self, *args):  # pragma: no cover
        return False


@pytest.fixture
def mock_neo4j() -> FakeNeo4jSession:
    return FakeNeo4jSession()


# ---------------------------------------------------------------------------
# Auth / RBAC fixtures
# ---------------------------------------------------------------------------

ROLE_SCOPES: dict[str, dict[str, Any]] = {
    "PSI": {
        "role": "sub_inspector",
        "station": "MG Road Police Station",
        "district": "Bengaluru Urban",
        "scope": "station",
        "masked_fields": ["complainant.phone", "complainant.address",
                          "victims.name"],
    },
    "SHO": {
        "role": "inspector",
        "station": "MG Road Police Station",
        "district": "Bengaluru Urban",
        "scope": "station",
        "masked_fields": ["complainant.phone"],
    },
    "DCP": {
        "role": "dcp",
        "station": None,
        "district": "Bengaluru Urban",
        "scope": "district",
        "masked_fields": [],
    },
}


def _encode_fake_token(claims: dict[str, Any]) -> str:
    """Produce a JWT-shaped string ``<header>.<payload>.sig`` for tests.

    The 'signature' is a constant — real verification is never called in
    unit/integration tests. The header is fixed and the payload carries
    every claim we need (role, station, scope, masked_fields).
    """
    header = base64.urlsafe_b64encode(
        json.dumps({"alg": "none", "typ": "JWT"}).encode("utf-8"),
    ).decode("ascii").rstrip("=")
    payload = base64.urlsafe_b64encode(
        json.dumps(claims, ensure_ascii=False).encode("utf-8"),
    ).decode("ascii").rstrip("=")
    return f"{header}.{payload}.sig"


def _decode_fake_token(token: str) -> dict[str, Any]:
    """Inverse of ``_encode_fake_token`` — used by ``mock_rbac_decode``."""
    try:
        _, payload_b64, _ = token.split(".")
    except ValueError:
        return {}
    pad = "=" * (-len(payload_b64) % 4)
    raw = base64.urlsafe_b64decode((payload_b64 + pad).encode("ascii"))
    return json.loads(raw.decode("utf-8"))


@pytest.fixture
def test_user_token() -> Callable[[str, str | None], str]:
    """Factory: ``test_user_token("PSI")`` returns a signed-shape token."""

    def _make(role: str, user_id: str | None = None) -> str:
        spec = ROLE_SCOPES.get(role.upper())
        if spec is None:
            raise ValueError(
                f"Unknown demo role: {role!r} (choose PSI, SHO, or DCP)",
            )
        claims = {
            "sub": user_id or f"user-{role.lower()}-001",
            "role": spec["role"],
            "station": spec["station"],
            "district": spec["district"],
            "scope": spec["scope"],
            "masked_fields": spec["masked_fields"],
            "iat": 1_750_000_000,
        }
        return _encode_fake_token(claims)

    return _make


@pytest.fixture
def mock_rbac_decode() -> Callable[[str], dict[str, Any]]:
    """Decoder for tokens minted by ``test_user_token``.

    Use this in tests instead of importing a real auth helper — keeps the
    test layer dependency-free.
    """
    return _decode_fake_token


# ---------------------------------------------------------------------------
# Misc helpers
# ---------------------------------------------------------------------------

@pytest.fixture
def integration_base_url() -> str:
    """Returns ``CATALYST_API_BASE`` or skips the test if unset.

    Integration-marked tests that need a live orchestrator URL pull this
    fixture; unit tests should never depend on it.
    """
    url = os.getenv("CATALYST_API_BASE", "").strip().rstrip("/")
    if not url:
        pytest.skip("CATALYST_API_BASE not set; skipping live integration test")
    return url


@pytest.fixture
def audio_fixtures_dir() -> Path:
    """Directory containing voice fixture files."""
    return AUDIO_FIXTURES_DIR


def has_kannada_chars(text: str) -> bool:
    """True if ``text`` contains at least one character in the Kannada block.

    Kannada Unicode block: U+0C80–U+0CFF.
    """
    return any("ಀ" <= ch <= "೿" for ch in text or "")


def has_latin_chars(text: str) -> bool:
    """True if ``text`` contains at least one ASCII letter."""
    return any(ch.isascii() and ch.isalpha() for ch in text or "")


# Re-export so test files can ``from conftest import has_kannada_chars``.
@pytest.fixture
def lang_helpers() -> dict[str, Callable[[str], bool]]:
    return {
        "has_kannada": has_kannada_chars,
        "has_latin": has_latin_chars,
    }
