"""Data quality + integrity tests for the synthetic FIR corpus.

These tests run against ``data/firs_sample.jsonl`` (the first 100 records
of the 50k synthetic FIR set generated by ``data/generate_synthetic_firs.py``).

What we assert:

* **Schema compliance** — every record carries the fields the downstream
  pipeline relies on (id, location, narrative bilingual pair, …)
* **Kannada Unicode coverage** — narrative_kannada must actually be
  Kannada, not transliterated Latin.
* **Realistic distribution** — petty crime (theft, vehicle_theft,
  burglary) outweighs serious crime (murder, etc.) by the order of
  magnitude you'd see in real NCRB-style data.
* **H3 indexing works** — every record's lat/lng yields a valid H3 cell
  string at resolution 8, which is what the hotspot pipeline uses.

All tests are pure data assertions — no network, no Catalyst, no Gemini.
"""

from __future__ import annotations

import re
from collections import Counter
from typing import Any

import pytest

from conftest import has_kannada_chars, has_latin_chars

pytestmark = [pytest.mark.unit, pytest.mark.data_quality]


# Fields every downstream tool reads. Adding more is fine, but breaking
# this contract should fail the test.
REQUIRED_TOP_LEVEL_FIELDS = {
    "fir_no",
    "station_name",
    "station_lat",
    "station_lng",
    "district",
    "date_registered",
    "time_registered",
    "crime_type",
    "ipc_sections",
    "location_lat",
    "location_lng",
    "complainant",
    "accused",
    "victims",
    "modus_operandi",
    "modus_operandi_kannada",
    "investigating_officer",
    "status",
    "linked_fir_nos",
    "narrative",
    "narrative_kannada",
}

REQUIRED_COMPLAINANT_FIELDS = {"name", "age", "gender", "phone", "address"}
REQUIRED_IO_FIELDS = {"name", "rank", "badge_no"}

# Karnataka bounding box (with some slack for coastal & northern districts).
KARNATAKA_LAT_RANGE = (11.5, 18.6)
KARNATAKA_LNG_RANGE = (74.0, 78.6)

VALID_STATUS = {
    "under_investigation",
    "chargesheet_filed",
    "closed",
    "disposed",
    "transferred",
    "pending",
}


# ---------------------------------------------------------------------------
# Schema
# ---------------------------------------------------------------------------

def test_sample_is_non_empty(sample_firs: list[dict[str, Any]]) -> None:
    assert len(sample_firs) >= 50, (
        f"firs_sample.jsonl has only {len(sample_firs)} rows; expect ≥50"
    )


def test_every_record_has_required_fields(
    sample_firs: list[dict[str, Any]],
) -> None:
    for i, rec in enumerate(sample_firs):
        missing = REQUIRED_TOP_LEVEL_FIELDS - set(rec.keys())
        assert not missing, (
            f"record {i} ({rec.get('fir_no')}) missing fields: {sorted(missing)}"
        )

        # Nested objects.
        comp_missing = REQUIRED_COMPLAINANT_FIELDS - set(rec["complainant"].keys())
        assert not comp_missing, (
            f"record {i} complainant missing: {comp_missing}"
        )

        io_missing = REQUIRED_IO_FIELDS - set(rec["investigating_officer"].keys())
        assert not io_missing, (
            f"record {i} investigating_officer missing: {io_missing}"
        )

        # Lists must be lists, not None.
        assert isinstance(rec["accused"], list), f"record {i} accused not list"
        assert isinstance(rec["victims"], list), f"record {i} victims not list"
        assert isinstance(rec["ipc_sections"], list), (
            f"record {i} ipc_sections not list"
        )
        assert isinstance(rec["linked_fir_nos"], list), (
            f"record {i} linked_fir_nos not list"
        )


def test_fir_no_pattern_and_uniqueness(
    sample_firs: list[dict[str, Any]],
) -> None:
    """FIR numbers should match STATION/YEAR/SEQ pattern and be unique."""
    pattern = re.compile(r"^[A-Z]{2,6}/\d{4}/\d{5}$")
    seen: set[str] = set()
    for rec in sample_firs:
        fir = rec["fir_no"]
        assert pattern.match(fir), f"FIR number off-pattern: {fir!r}"
        assert fir not in seen, f"duplicate FIR number: {fir}"
        seen.add(fir)


def test_coordinates_within_karnataka(
    sample_firs: list[dict[str, Any]],
) -> None:
    lat_lo, lat_hi = KARNATAKA_LAT_RANGE
    lng_lo, lng_hi = KARNATAKA_LNG_RANGE
    for rec in sample_firs:
        for lat_key, lng_key in [
            ("station_lat", "station_lng"),
            ("location_lat", "location_lng"),
        ]:
            lat, lng = rec[lat_key], rec[lng_key]
            assert lat_lo <= lat <= lat_hi, (
                f"{rec['fir_no']} {lat_key}={lat} outside Karnataka"
            )
            assert lng_lo <= lng <= lng_hi, (
                f"{rec['fir_no']} {lng_key}={lng} outside Karnataka"
            )


def test_status_values_are_known(sample_firs: list[dict[str, Any]]) -> None:
    bad = [
        (rec["fir_no"], rec["status"])
        for rec in sample_firs
        if rec["status"] not in VALID_STATUS
    ]
    assert not bad, f"unknown status values: {bad[:5]}"


# ---------------------------------------------------------------------------
# Kannada coverage
# ---------------------------------------------------------------------------

def test_kannada_narrative_actually_in_kannada(
    sample_firs: list[dict[str, Any]],
) -> None:
    """Every narrative_kannada must contain Kannada Unicode characters.

    Some Latin (names, IPC numbers, place names) is fine — but a record
    with zero Kannada Unicode would mean the generator dropped a row.
    """
    no_kannada = [
        rec["fir_no"] for rec in sample_firs
        if not has_kannada_chars(rec.get("narrative_kannada", ""))
    ]
    assert not no_kannada, (
        f"{len(no_kannada)} records have no Kannada in narrative_kannada; "
        f"first 5: {no_kannada[:5]}"
    )


def test_kannada_modus_operandi_in_kannada(
    sample_firs: list[dict[str, Any]],
) -> None:
    no_kn = [
        rec["fir_no"] for rec in sample_firs
        if not has_kannada_chars(rec.get("modus_operandi_kannada", ""))
    ]
    assert not no_kn, (
        f"{len(no_kn)} records have no Kannada in modus_operandi_kannada"
    )


def test_kannada_unicode_block_coverage(
    sample_firs: list[dict[str, Any]],
) -> None:
    """At least 30 distinct Kannada code points should appear across the sample.

    A trivially small set (say < 10) would mean the generator only uses
    a single canned phrase and translations are useless for retrieval.
    """
    kn_chars: set[str] = set()
    for rec in sample_firs:
        for ch in rec.get("narrative_kannada", ""):
            if "ಀ" <= ch <= "೿":
                kn_chars.add(ch)
    assert len(kn_chars) >= 30, (
        f"only {len(kn_chars)} distinct Kannada code points used; "
        f"generator may be too repetitive"
    )


def test_english_narrative_predominantly_ascii(
    sample_firs: list[dict[str, Any]],
) -> None:
    """English narrative shouldn't accidentally contain Kannada Unicode."""
    leaks = [
        rec["fir_no"]
        for rec in sample_firs
        if has_kannada_chars(rec.get("narrative", ""))
    ]
    assert not leaks, (
        f"English narrative leaked Kannada Unicode: {leaks[:5]}"
    )


# ---------------------------------------------------------------------------
# Distributions
# ---------------------------------------------------------------------------

def test_crime_type_distribution_is_realistic(
    sample_firs: list[dict[str, Any]],
) -> None:
    """Petty crime should outweigh serious crime by at least 5x.

    NCRB Karnataka 2022 ratio for theft-family : murder is roughly 100:1;
    we'll just demand >5:1 to keep the test robust to sampling noise on
    a 100-record window.
    """
    crime_counts = Counter(rec["crime_type"] for rec in sample_firs)
    # Sum the petty/property crime families that should dominate.
    property_crimes = sum(
        crime_counts.get(c, 0) for c in (
            "theft", "vehicle_theft", "burglary", "chain_snatching",
            "pickpocketing", "house_break_in",
        )
    )
    serious_crimes = sum(
        crime_counts.get(c, 0) for c in (
            "murder", "rape", "kidnapping", "rioting", "dacoity",
        )
    )
    if serious_crimes == 0:
        # Pure petty-crime corpus also acceptable for the sample window.
        assert property_crimes > 0, f"no crimes at all? {crime_counts}"
        return
    ratio = property_crimes / max(serious_crimes, 1)
    assert ratio >= 5, (
        f"crime mix unrealistic: property={property_crimes} "
        f"serious={serious_crimes} ratio={ratio:.2f}; counts={dict(crime_counts)}"
    )


def test_at_least_three_districts_represented(
    sample_firs: list[dict[str, Any]],
) -> None:
    """Karnataka has 31 districts; a 100-record sample should hit several."""
    districts = {rec["district"] for rec in sample_firs}
    assert len(districts) >= 3, (
        f"only {len(districts)} districts represented: {districts}"
    )


def test_at_least_two_years_represented(
    sample_firs: list[dict[str, Any]],
) -> None:
    """Trend queries need multi-year data."""
    years = {rec["date_registered"][:4] for rec in sample_firs}
    assert len(years) >= 2, f"only one year present: {years}"


def test_complainant_phone_is_masked(
    sample_firs: list[dict[str, Any]],
) -> None:
    """Generator should already mask phone numbers (privacy by default)."""
    leaks = [
        rec["fir_no"]
        for rec in sample_firs
        if rec["complainant"].get("phone")
        and not re.search(r"X{4,}", rec["complainant"]["phone"])
    ]
    assert not leaks, (
        f"{len(leaks)} complainant phones not masked; first 5: {leaks[:5]}"
    )


# ---------------------------------------------------------------------------
# H3 indexing
# ---------------------------------------------------------------------------

def test_h3_indexing_works_on_every_record(
    sample_firs: list[dict[str, Any]],
) -> None:
    """Every (location_lat, location_lng) must yield a valid H3 res-8 cell.

    If the ``h3`` package isn't installed we skip — the hotspot pipeline
    is the only place that needs it and it's optional for unit runs.
    """
    h3 = pytest.importorskip("h3", reason="h3 package not installed")

    cells: set[str] = set()
    for rec in sample_firs:
        # h3-py 4.x exposes ``latlng_to_cell``; older 3.x uses ``geo_to_h3``.
        latlng_to_cell = getattr(h3, "latlng_to_cell", None) or getattr(
            h3, "geo_to_h3", None,
        )
        assert latlng_to_cell is not None, "h3 API surface unknown"
        cell = latlng_to_cell(rec["location_lat"], rec["location_lng"], 8)
        assert isinstance(cell, str) and len(cell) >= 10, (
            f"{rec['fir_no']} bad H3 cell: {cell!r}"
        )
        cells.add(cell)

    # With 100 FIRs scattered across Karnataka we expect lots of unique cells.
    assert len(cells) >= 20, (
        f"only {len(cells)} unique H3 cells — geo distribution too clumpy"
    )
