#!/usr/bin/env bash
# =============================================================================
# Sarvik — one-shot .env setup helper
# Usage:
#   1. Generate a fresh auth code at https://api-console.zoho.in
#      → click your Self Client → Generate Code tab → scope: ZohoCatalyst.projects.ALL
#      → expiry: 10 minutes → CREATE → copy the code (looks like 1000.xxxx.xxxx)
#   2. Get Gemini key from https://aistudio.google.com/apikey
#   3. Get Google Maps key from https://console.cloud.google.com/google/maps-apis/credentials
#   4. Create Neo4j AuraDB Free at https://console.neo4j.io
#   5. Fill the 4 prompts below — values are not echoed
#   6. Script exchanges the auth code, writes a complete .env, deletes any temp files
# =============================================================================
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/backend/.env"

# --- Static values (Catalyst self-client already created) ---
CATALYST_ORG_ID="60074155874"
CATALYST_PROJECT_ID="47060000000020024"
CATALYST_CLIENT_ID="***CATALYST_CLIENT_ID_REDACTED***"
CATALYST_CLIENT_SECRET="***CATALYST_CLIENT_SECRET_REDACTED***"
CATALYST_TOKEN_ENDPOINT="https://accounts.zoho.in/oauth/v2/token"

echo
echo "Sarvik .env setup"
echo "=================="
echo "This will overwrite $ENV_FILE"
echo

read -srp "1/4 Fresh Zoho auth code (from api-console.zoho.in): " AUTH_CODE
echo
read -srp "2/4 Gemini API key: " GEMINI_API_KEY
echo
read -srp "3/4 Google Maps API key: " GOOGLE_MAPS_API_KEY
echo
read -rp  "4a/4 Neo4j URI (e.g. neo4j+s://xxxx.databases.neo4j.io): " NEO4J_URI
read -srp "4b/4 Neo4j password: " NEO4J_PASSWORD
echo

# --- Exchange auth code for refresh token ---
echo "Exchanging auth code with Zoho..."
RESP=$(curl -sS -X POST "$CATALYST_TOKEN_ENDPOINT" \
  -d "grant_type=authorization_code" \
  -d "client_id=$CATALYST_CLIENT_ID" \
  -d "client_secret=$CATALYST_CLIENT_SECRET" \
  -d "code=$AUTH_CODE")

REFRESH=$(echo "$RESP" | python -c "import json,sys;d=json.load(sys.stdin);print(d.get('refresh_token',''))" 2>/dev/null || echo "")

if [ -z "$REFRESH" ]; then
    ERR=$(echo "$RESP" | python -c "import json,sys;d=json.load(sys.stdin);print(d.get('error','unknown'))" 2>/dev/null || echo "parse-error")
    echo
    echo "ERROR: token exchange failed — $ERR"
    echo "Likely: the auth code is expired or already used. Generate a fresh one."
    exit 1
fi
echo "Got refresh_token (${#REFRESH} chars)"

# --- Write .env atomically (single python call, no temp files) ---
python <<PYEOF
content = '''# =============================================================================
# Sarvik backend — REAL credentials (DO NOT COMMIT — gitignored)
# Generated by app/scripts/setup-env.sh
# =============================================================================

# Zoho Catalyst — Sarvik project (India DC)
CATALYST_ORG_ID=$CATALYST_ORG_ID
CATALYST_PROJECT_ID=$CATALYST_PROJECT_ID
CATALYST_PROJECT_DOMAIN=https://api-console.catalyst.zoho.in
CATALYST_ENVIRONMENT=Development
CATALYST_API_BASE=https://sarvik-development.catalystserverless.in

CATALYST_CLIENT_ID=$CATALYST_CLIENT_ID
CATALYST_CLIENT_SECRET=$CATALYST_CLIENT_SECRET
CATALYST_REFRESH_TOKEN=$REFRESH
CATALYST_TOKEN_ENDPOINT=$CATALYST_TOKEN_ENDPOINT
CATALYST_API_DOMAIN=https://www.zohoapis.in

CATALYST_AUDIT_TABLE=audit_log
CATALYST_SESSION_TABLE=session_state

# Google Gemini
GEMINI_API_KEY=$GEMINI_API_KEY
GEMINI_TEXT_MODEL=gemini-2.5-pro
GEMINI_EMBED_MODEL=gemini-embedding-001
GEMINI_LIVE_MODEL=gemini-live-2.5-flash-preview
GEMINI_MAX_RETRIES=3
GEMINI_RETRY_BACKOFF_S=0.6

# Neo4j AuraDB
NEO4J_URI=$NEO4J_URI
NEO4J_USERNAME=neo4j
NEO4J_PASSWORD=$NEO4J_PASSWORD
NEO4J_DATABASE=neo4j
NEO4J_MAX_POOL=20
NEO4J_ACQUIRE_TIMEOUT_S=30

# Google Cloud
GOOGLE_APPLICATION_CREDENTIALS=./secrets/gcp-service-account.json
GOOGLE_CLOUD_PROJECT=ksp-saathi-2026
GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY

LOG_LEVEL=INFO
SYNTH_FORCE_MODEL=
'''
import os
os.makedirs(os.path.dirname("$ENV_FILE"), exist_ok=True)
with open("$ENV_FILE", "w", encoding="utf-8") as f:
    f.write(content)
print(f"Wrote $ENV_FILE ({len(content)} bytes)")
PYEOF

echo
echo "SUCCESS — .env is ready."
echo
echo "Next steps:"
echo "  1. cd app/backend"
echo "  2. npm install -g zcatalyst-cli   # if not already"
echo "  3. catalyst login                  # browser auth (no token needed for local deploy)"
echo "  4. catalyst deploy --only functions:hello   # smoke test"
echo
